### ISSUE TITLE
repeated validation of arrays and nested objects

### ISSUE THREAD

**Issue by RomanCedric** [cwacek/python-jsonschema-objects#143]
I m dealing with big objects, some made of nested objects and arrays of objects.
Initialization of such objects can get veeery long, and it seems that many values are validated multiple times.
Each literal value is validated when set, each array re-validates its elements, each object re-validates its properties and nested objects. When initializing an object with a big nested dictionary, it can take a very long time, mostly spent in validation already done.

How could we change the validation mechanism to avoid this?

Constraints I see:
+ for the moment, some construction steps are done during validation (typed_elems are set during validation)

Ideas:
+ add a "validated/dirty" flag in literals to avoid to validate a value already validated
+ only validate dirty properties

Any other ideas? any side effects to consider?

**Comment by cwacek** [comment]
It seems to me an extension of the existing `strict` flag when building objects could work. Currently that flag extends validation to include checking whether all required properties are set, but I could envision a `lazy_validate` that does the opposite and doesnt validate anything until asked to. Some kind of `validated` flag would probably be the necessary solution.

One place this may cause problems is where `oneOf` is used, because validation is used to match against the set of valid types.

**Comment by RomanCedric** [comment]
I ve investigated the situation. Adding a "validated" on literals flag makes a huge difference. 
There s also a problem with the ArrayWrapper validation: 
_typed is updated and _dirty set to False only when accessing the property typed_elem (ie when iterating or accessing an element of the array).  => if you call validate_items(), you recreate valid elements but _dirty is left to the same value and _typed not updated.
Is there a reason when don't set _typed and _dirty=False in validate_items ?

**Comment by cwacek** [comment]
So I think my logic there was that you always want `validate_items` to do the right thing (i.e. actually validate), so the dirty checking only comes into play if you actually try to access the elements. However, you're probably right, `validate_items` could also *set* the _typed and _dirty flags as long as it doesn't check them. 

I think the ArrayWrapper also needs a `validated` flag to gate the `validate` function, since that doesn't need to be called repeatedly.

**Comment by RomanCedric** [comment]
Isn't `_dirty` the opposite of `validated` ? I think we could use it as a the `validated` flag
I had added a test on `if not _dirty: return True` in validate_items() which was avoiding most of the redundant validations. I was wondering why there were some left and it s because validate doesn't update _dirty and _typed

I d like to make a fix but I m working on a fork (very different by now and I messed up with some branches), and the case i m using to debug won't be easy to reproduce with the actual library.

**Comment by cwacek** [comment]
So I explicitly don't want to make `validate_items` only have an effect if dirty. That function should always do the right thing (i.e. actually perform the validation). However, I think we can end up with the desired result either way. I'll see if I can implement what I'm thinking in a sec here.
