### ISSUE TITLE
Support for the "format" field from JSON spec

### ISSUE THREAD

**Issue by surbas** [cwacek/python-jsonschema-objects#2]
Any thoughts to if you are going to support validation type "format" and type coercion based on that?
Would you be open to a pull request that add such a thing, if you are not interested?

**Comment by davidbargeron** [comment]
I was thinking of implementing support for the "format" field by importing the jsonschema package in validators.py and calling its format validator. If jsonschema is not present on the machine, then the import will fail silently and any format specifications won't be validated (which satisfies the jsonschema spec); otherwise, if it is present, then we get basic format validation as supported by the jsonschema package. Any opinions/advice/guidance wrt this approach?
