### ISSUE TITLE
Consider "None" as a valid string type

### ISSUE THREAD

**Issue by RamseyK** [cwacek/python-jsonschema-objects#24]
Many external systems/libraries (sqlite) interchange None and empty strings. When directly assigning a jsonschema object string attribute, the check_string_type will throw a validation error if the value is None. Working around this requires a conversion of all None's to empty strings or verbose None checks before assignment.

Would it make sense to safely modify check_string_type to ignore any 'None' values instead of throwing an error?

**Comment by cwacek** [comment]
I think the issue is that the jsonschema object created is trying to represent something that is valid according to the JSON Schema that created the object. `None` is not a valid string according to the JSON Schema, so allowing `None` doesn't make sense. We could convert all `None` values to `"None"` strings, but that seems a little hokey to me.

Unless I'm misunderstanding, the appropriate thing to do would be to not attempt to store None attributes received from something like SQLite (since those represent nonexistent values anyway)

**Comment by sebastroy** [comment]
I agree with @cwacek the proper "None" value in the JSON standard is *null*. To be a valid string None should be surrounded by double quotes. Be mindful that the string "None" is not the same as "" in general. Wherever the None value comes from should be changed either to nul or "" before serializing to json.
