### ISSUE TITLE
`any_of='use-first'` not working

### ISSUE THREAD

**Issue by kurtrwall** [cwacek/python-jsonschema-objects#297]
**Describe the bug**
Btw, great library, thanks for making it!

I'm trying to use this with draft 6 jsonschema (Microsoft's [AdaptiveCard schema](https://adaptivecards.io/schemas/adaptive-card.json), and I'm still getting:
```
NotImplementedError: anyOf is not supported as bare property (workarounds available by setting any_of flag)
```
**Example Schema and code**
```python
import python_jsonschema_objects as pjs
import requests
schema = requests.get('https://adaptivecards.io/schemas/adaptive-card.json').json()
ns = builder.build_classes(any_of='use-first')
...snip
NotImplementedError: anyOf is not supported as bare property (workarounds available by setting any_of flag)
```

**Expected behavior**
The schema was parsed and the classes were generated.

**Comment by cwacek** [comment]
Hey @kurtrwall, I've got a PR that fixes your issue, but it highlighted a different one in the adaptive-card.json schema. Do you happen to know what one is supposed to do with these invalid properties: https://github.com/cwacek/python-jsonschema-objects/pull/301/files#diff-3c302bf352d3c575ff7e419df154d494c77f837be3f00e9e4b350b0ec7d99779R35-R43

As far as I can tell reading the spec, at a minimum you are required to provide the `type` key for any properties, and those ones are just empty objects. The library is now bailing out attempting to parse the schema because there's no definition.

**Comment by cwacek** [comment]
This might be a broader issue with Microsoft's AdaptiveCard: https://github.com/microsoft/AdaptiveCards/discussions/8943

Going to mark as xfail for now, so I can merge the PR because the underlying issue was real.

**Comment by kurtrwall** [comment]
Thanks for looking at this, hopefully they address it soon or at least take a look at that linked issue...
