### ISSUE TITLE
RPM build failed: python3 setup.py bdist_rpm

### ISSUE THREAD

**Issue by vit0rg** [cwacek/python-jsonschema-objects#31]
**ACTIONS**

wget 'https://pypi.python.org/packages/source/p/python_jsonschema_objects/python_jsonschema_objects-0.0.15.tar.gz#md5=13a9ee120bf0ba0356ec562ee9ae94ec'
tar -xzf python_jsonschema_objects-0.0.15.tar.gz
cd python_jsonschema_objects-0.0.15/
python3 setup.py bdist_rpm

**RESULT**

requirements.txt
running bdist_rpm
running egg_info
...
byte-compiling /tmp/python_jsonschema_objects-0.0.15/build/bdist.linux-x86_64/rpm/BUILDROOT/python_jsonschema_objects-0.0.15-1.x86_64/usr/lib/python3.4/site-packages/test/test_util.py to test_util.cpython-34.pyc
  File "/usr/lib/python3.4/site-packages/test/test_util.py", line 0
SyntaxError: unknown encoding: spec

writing byte-compilation script '/tmp/tmppszppvxh.py'
/usr/bin/python3 -O /tmp/tmppszppvxh.py
  File "/usr/lib/python3.4/site-packages/test/test.py", line 0
SyntaxError: unknown encoding: spec

  File "/usr/lib/python3.4/site-packages/test/test_util.py", line 0
SyntaxError: unknown encoding: spec
...
error: command 'rpmbuild' failed with exit status 1

**Comment by vit0rg** [comment]
After this command everything works fine:
rm -rf test/test*

**Comment by cwacek** [comment]
Due to my discovering it about the time I wrote this, the tests are written in [nose of yeti](https://github.com/delfick/nose-of-yeti). That uses a special decoder to allow tests to be written in RSpec style. However if nose of yeti isn't installed, trying to byte compile this is likely to fail.

A few thoughts:

1. `rm -rf test/test*` works because it just deletes the files with the weird encoding. If you don't care about having the tests in the rpm
2. Installing nose-of-yeti will also fix the problem because then the encoding will be available

Either way, this isn't an issue with python-jsonschema-objects

**Comment by vit0rg** [comment]
I see now, however it took some time for me to find that out, so i guess there should be:
1. More informative error message with required components list.
and/or
2. Skip this step as optional and print warning, but continue build.

**Comment by cwacek** [comment]
This isn't an issue for bdist_egg, bdist_wheel, or sdist, so this is an issue particular to bdist_rpm, and if it needs to be skipped then that's bdist_rpm's problem. 

The setup function explicitly *excludes* tests, so I think bdist_rpm must not properly handle that configuration.
