### ISSUE TITLE
Class names in namespace

### ISSUE THREAD

**Issue by iimre** [cwacek/python-jsonschema-objects#63]
It is quite wired that every title and id converted.
For example:
FooBar -> Foobar
Foo Bar -> FooBar
foo_bar -> FooBar

My proposal would be that that conversion shall be done only for title. So if user give an 'id' for the schema object it shall be used as class name without any modification. In case of this 'id' is not a valid python identifier then builder shall throw an appropriate exception instead of converting it silently.

**Comment by cwacek** [comment]
I agree that this behavior is a little odd, but if you want to do
attribute-style access to the classes it's required because otherwise you
get invalid Python identifiers. Throwing an exception if naming conversion
fails is a no-go because it requires changes to otherwise working schemas.

You can already get the class by directly asking for it by URI:

```
builder = pjo.ObjectBuilder(schema)
builder.build_classes()
builder.get_class("#/definitions/model")
```
