### ISSUE TITLE
Hard coding specific version of dependencies is problematic

### ISSUE THREAD

**Issue by itamarst** [cwacek/python-jsonschema-objects#69]
`requirements.txt` currently hardcodes jsonschema 2.3.0. That means I *have* to use it when using automated packaging tools like pip (or in my case `pex`).

jsonschema is up to version 2.5.1 though, so I can't use newer jsonschema at the same time as python-jsonschema-objects.

As an alternative I suggest requirements.txt include a minimal version, e.g. `jsonschema>=2.3.0`.

**Comment by blr246** [comment]
`requirements.txt` should contain pinned versions for people needing to reproduce exactly a known working environment.

One possible fix is to add a `requirements.in` file having the widest possible working version ranges for all library dependencies. These should be used verbatim in `setup.py`'s `install_requires` so that library clients do not get stuck with pinned versions. The useful (yet at times buggy) `pip-tools` allows you to `pip-compile` a `requirements.in` into a pinned `requirements.txt`, which you can commit to the repo alongside `requirements.in`.

Using the above, you get both the certain reproducibility of pinned versions and the proper declaration of dependencies so that library clients can resolve their own pinned versions.

**Comment by itamarst** [comment]
1. To be clear I don't care about `requirements.txt` as such, just about what happens when you do `pip install`. So setup.py differing from `requirements.txt` makes sense to me.
2. (The use case of reproducable environment makes sense for applications. Not sure it makes sense in libraries. But that's incidental.)

**Comment by cwacek** [comment]
Once again a reminder that Python dependency specification is awful.
Something like [pipfile](https://github.com/pypa/pipfile) cannot come soon
enough.

@blr246's suggestion to move the requirements.txt => requirements.in and
use that to generate both setup.py install_requires and requirements.txt
seems like a good one. I wasn't aware of pip-tools ability to do that.

@itamarst I'll make that change as soon as I get a chance to, but I'm more
than happy to merge PRs if you want that change to happen on your timeframe
instead of mine.

**Comment by itamarst** [comment]
Thanks! If it gets urgent I'll see what I can do.

Can you expand on what you mean re pip-tools? Or to put it another way, what does "generate requirements.txt" mean? Is it checked in to git? And if so, why?

**Comment by itamarst** [comment]
FWIW approach I've taken is testing different versions of dependencies. So e.g. https://github.com/itamarst/crochet/blob/master/.travis.yml - runs with latest Twisted and Twisted 15.0.0, and requirements are `Twisted>=15.0.0`.

**Comment by blr246** [comment]
`pip-tools` is a package (`$ pip install pip-tools`) that includes a Python dependency resolver called `pip-compile`.

The dependency resolution algorithm proceeds in stages, incorporating at each round the next set of version specifiers pulled in by the current set of packages. In other words, it's a BFS on the dependency graph. Each package also carries a merged version specified for the smallest range of versions satisfying the entire dependency graph. When the BFS terminates, the versions are resolved to the most recent version satisfying every dependency, and then output into a generated `requirements.txt`. If no versions satisfy a package range, then the compilation fails. By convention, the input to `pip-compile` is called `requirements.in`.

It's advantageous to commit pinned versions for development, even it it's just a library. As you've already pointed out, the `install_requires` list should never be pinned versions, as it easily breaks library clients.
