### ISSUE TITLE
Creation of array anonymous objects fails

### ISSUE THREAD

**Issue by demosdemon** [cwacek/python-jsonschema-objects#8]
It seems [classbuilder.py:485](https://github.com/cwacek/python-jsonschema-objects/tree/2a6f5af53e69a99a01d867285dd2f138a26549bd/python_jsonschema_objects/classbuilder.py#L485) is passing the whole array `detail['items']` to `construct` when it should be passing `elem` from the enumeration.

**Comment by cwacek** [comment]
@demosdemon Sorry for the wildly delayed response - did you have a example of this that I could use as a test case?

**Comment by fre-sch** [comment]
Classbuilder.py has changed since @demosdemon opened this, line 485 from original comment is now [classbuilder.py:617](https://github.com/cwacek/python-jsonschema-objects/blob/master/python_jsonschema_objects/classbuilder.py#L617)

Versions:
- `python-jsonschema-objects==0.0.22.post1`
- `jsonschema==2.3.0`

```python
import python_jsonschema_objects as pjo


schema = {
    'title': 'Example',
    'properties': {
        'stringProp': { 'type': 'string' },
        'arrayProp': {
            'type': 'array',
            'items': {
                'type': 'string',
            }
        }
    }
}

builder = pjo.ObjectBuilder(schema)
ns = builder.build_classes()
Example = ns.Example
instance = Example(
    stringProp='This seems fine',
    arrayProp=['these', 'are', 'problematic']
)

print("(As expected) stringProp:", instance.stringProp)
### prints:
#stringProp: This seems fine

print("(As expected) stringProp == 'This seems fine':",
    instance.stringProp == 'This seems fine')
### prints:
#(As expected) stringProp == 'This seems fine': True

print("arrayProp:", instance.arrayProp)
### prints:
#arrayProp: [<example/arrayProp_<anonymous_field> these>, <example/arrayProp_<anonymous_field> are>, <example/arrayProp_<anonymous_field> problematic>]

print("arrayProp[0] == 'these': ", instance.arrayProp[0] == 'these')
### prints:
#arrayProp[0] == 'these':  False

print("str(arrayProp[0]) == 'these': ", str(instance.arrayProp[0]) == 'these')
### prints:
#str(arrayProp[0]) == 'these':  True

print("using str on items:", [str(i) for i in instance.arrayProp])
### prints:
#using str on items: ['these', 'are', 'problematic']
```

For me, having to use `str(item[0])` on properties defined as `{"type": "array", "items": {"type": "string"}}` was unexpected.

**Comment by cwacek** [comment]
Huh. That is a little odd. The properties are not actually strings (because they need to be wrapped), but they should compare okay - I'll look into it shortly.

**Comment by cwacek** [comment]
@fre-sch I've identified a partial fix for what you identified and will be pushing it shortly.

I'm guessing you were using Python 3, because the list-item comparators were failing due to the fact that Python 3 doesn't support __cmp__ and `classbuilder.LiteralValue` didn't define the correct alternatives (__eq__, __hash__ and __lt__).

This does *not* fix the issue where you have to cast list items to strings directly. This is a [known](https://www.python.org/dev/peps/pep-3140/) [issue](https://mail.python.org/pipermail/python-ideas/2013-April/020159.html), where calling `str(container)` results in calling `repr` on each container element, not `str`. I don't want to change the `repr` behavior for LiteralValues, because that would be wildly confusing, so unfortunately you'll just have to keep casting them to strings. I did add a `__str__` method to `LiteralValue`, so at least doing `str(item[0])` should result in what you expect.
